---
dataset:
  annot_dir: null
  create_zip: null
  data_dir_name: null
  downsample_factor: null
  downsample_size: null
  slide_dir: null
  use_augment: null
heatmaps:
  alpha: null
  blur: null
  cmap: null
  overlap: null
  patch_size: null
  percentile_scale: null
  percentile_score: null
trainer:
  exp_base_dir: null
  folds: null
  gpu: null
  model_args:
    batch_size: null
    data_dir: null
    exp_dir: null
    exp_name: null
    max_epochs: null
  model_params:
    freeze_ratio: null
    learning_rate: null
    patience: null
    start_from_epoch: null
  overwrite_preds: null
  use_augment: null