---
dataset:
  annot_dir: null
  create_zip: null
  data_dir_name: null
  downsample_factor: null
  downsample_size: null
  n_splits: null
  overlap: null
  patch_size: null
  save_slides: null
  slide_dir: null
  use_augment: null
gpu:
  device_index: null
heatmaps:
  alpha: null
  blur: null
  cmap: null
  downsample_factor: null
  downsample_size: null
  file_extension: null
  invert_preds: null
  overlap: null
  patch_dims: null
  percentile_scale: null
  percentile_score: null
  save_dir: null
  source_dir: null
  source_dir_annot: null
  use_plt: null
model:
  _select: null
  model-CLAM_SB:
    dropout: null
    k_sample: null
    learning_rate: null
    loss_weights:
      bag: null
      instance: null
  model-EfficientNetB0:
    freeze_ratio: null
    learning_rate: null
    patience: null
    start_from_epoch: null
  model-MobileNet:
    freeze_ratio: null
    learning_rate: null
    patience: null
    start_from_epoch: null
  model-ResNet50:
    freeze_ratio: null
    learning_rate: null
    patience: null
    start_from_epoch: null
  model-VGG16:
    freeze_ratio: null
    learning_rate: null
    patience: null
    start_from_epoch: null
summary:
  exp_names: null
trainer:
  batch_size: null
  data_dir: null
  exp_base_dir: null
  exp_name: null
  folds: null
  max_epochs: null
  overwrite_preds: null
  patch_dims: null
  predictions_file: null
  subset_size: null
  use_augment: null